# Generated by Django 5.2.5 on 2025-10-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=200),
        ),
    ]
